### ISSUE TITLE
Browser Error, why?

### ISSUE THREAD

**Issue by ezar** [shbatm/MMM-Logging#3]
I receive this notification error. Do you know why?
```
2019-03-16T06:30:00 <log> Browser Error: {
   "isTrusted": true
} (/home/pi/MagicMirror/modules/MMM-Logging/node_helper.js:37 Class.socketNotificationReceived)

```

**Comment by shbatm** [comment]
Something is throwing an error in the web browser console (DevTools /
Ctrl+Shift+I). The logging module is just reporting it back to the server
console / Pm2 logs.

**Comment by ezar** [comment]
I find the error in MMM-LocalTemperature module :)
Regards!

**Comment by dathbe** [comment]
> I find the error in MMM-LocalTemperature module :)
> Regards!

What exactly did you find?  I don't know what I'd be looking for.  I'm getting the same error, and it says it's with MMM-NestRemoteThermostat.  Is there a fix?
